import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarControl from "./components/navbar";
import SidebarControl from "./components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <div className="flex flex-col min-h-screen">
            <NavbarControl />
            <div className="flex flex-row min-w-full py-5">
              <SidebarControl />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
